spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username:
    password:

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create-drop # Change to "create-drop" to recreate tables on every application start
    show-sql: true

cloudinary:
  cloud-name: dmkelwf5l
  api-key: 626283538119945
  api-secret: W3h0cOWAr_CiqKggPCrIhJVOLTM